"use client";

import Script from 'next/script';

export default function Page() {
  return (
    <>
      <Script src="/webos/js/config.js" strategy="lazyOnload"  />
      <Script src="/webos/js/api.js" strategy="lazyOnload"  />
      <Script src="/webos/js/landing-auth.js" strategy="lazyOnload"  />
      <head dangerouslySetInnerHTML={{ __html: "\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Anand Web OS - Your Personal Web Operating System</title>\n    <link rel=\"stylesheet\" href=\"/webos/css/landing.css\">\n" }} />
      <div dangerouslySetInnerHTML={{ __html: "\n    <div class=\"landing-container\">\n        <div class=\"hero-section\">\n            <div class=\"hero-left\">\n                <h1 class=\"hero-title\">Your Personal Web Operating System</h1>\n                <p class=\"hero-subtitle\">\n                    A complete productivity suite featuring intelligent notes, file management,\n                    AI-powered assistance, and powerful admin tools. Everything you need in one place.\n                </p>\n\n                <div class=\"features-grid\">\n                    <div class=\"feature-card\">\n                        <div class=\"feature-icon\">📝</div>\n                        <h3>Smart Notes</h3>\n                        <p>Organize thoughts with powerful note-taking and search capabilities</p>\n                    </div>\n                    <div class=\"feature-card\">\n                        <div class=\"feature-icon\">📁</div>\n                        <h3>File Manager</h3>\n                        <p>Store and manage your files securely in the cloud</p>\n                    </div>\n                    <div class=\"feature-card\">\n                        <div class=\"feature-icon\">🤖</div>\n                        <h3>AI Assistant</h3>\n                        <p>Get instant help from your personal AI-powered assistant</p>\n                    </div>\n                </div>\n            </div>\n\n            <div class=\"hero-right\">\n                <div class=\"login-card\">\n                    <h2>Welcome Back</h2>\n                    <p class=\"login-subtitle\">Sign in to access your workspace</p>\n\n                    <form id=\"loginForm\" onsubmit=\"handleLogin(event)\">\n                        <div class=\"form-group\">\n                            <label for=\"email\">Email</label>\n                            <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"your@email.com\" required=\"\" autocomplete=\"email\">\n                        </div>\n\n                        <div class=\"form-group\">\n                            <label for=\"password\">Password</label>\n                            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required=\"\" autocomplete=\"current-password\">\n                        </div>\n\n                        <div id=\"errorMessage\" class=\"error-message\"></div>\n\n                        <button type=\"submit\" class=\"btn-login\" id=\"loginBtn\">\n                            Sign In\n                        </button>\n                    </form>\n\n                    <div class=\"register-link\">\n                        Don't have an account? <a href=\"./register/\">Create one</a>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </div>\n\n    \n    \n    \n\n\n" }} suppressHydrationWarning />
    </>
  );
}
