"use client";

import Script from 'next/script';

export default function Page() {
  return (
    <>
      <Script src="/birthday/script.js?v=20250313145600" strategy="lazyOnload"  />
      <head dangerouslySetInnerHTML={{ __html: "\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>For Abhilasha</title>\n  <meta name=\"description\" content=\"A romantic birthday chat surprise for Abhilasha.\">\n  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"\">\n  <link href=\"https://fonts.googleapis.com/css2?family=Great+Vibes&amp;family=Playfair+Display:wght@400;700&amp;family=Inter:wght@400;500;600;700&amp;family=Poppins:wght@400;500;600;700&amp;display=swap\" rel=\"stylesheet\">\n  <link rel=\"stylesheet\" href=\"/birthday/style.css\">\n" }} />
      <div dangerouslySetInnerHTML={{ __html: "\n  <div class=\"ambient\" aria-hidden=\"true\">\n    <div class=\"ambient__glow ambient__glow--one\"></div>\n    <div class=\"ambient__glow ambient__glow--two\"></div>\n    <div class=\"ambient__glow ambient__glow--three\"></div>\n  </div>\n\n  <div id=\"floating-hearts\" class=\"floating-hearts\" aria-hidden=\"true\"></div>\n  <div id=\"confetti-layer\" class=\"confetti-layer\" aria-hidden=\"true\"></div>\n\n  <main class=\"experience\">\n    <section id=\"intro-screen\" class=\"intro-screen\" aria-label=\"Birthday Intro\">\n      <div class=\"intro-screen__content\">\n        <p class=\"intro-line\" data-line=\"1\">28 March</p>\n        <p class=\"intro-line\" data-line=\"2\">A very special day</p>\n        <p class=\"intro-line\" data-line=\"3\">Because someone special was born</p>\n        <h1 class=\"intro-line intro-line--name\" data-line=\"4\">Abhilasha</h1>\n        <button id=\"open-chat\" class=\"open-chat\" type=\"button\">Open your birthday chat</button>\n      </div>\n    </section>\n\n    <section id=\"chat-screen\" class=\"chat-screen\" aria-label=\"Birthday Chat\">\n      <div class=\"chat-card\">\n        <header class=\"chat-header\">\n          <div class=\"chat-header__avatar\">A</div>\n          <div class=\"chat-header__meta\">\n            <h2>Abhilasha <span aria-hidden=\"true\">❤</span></h2>\n            <p>online</p>\n          </div>\n        </header>\n\n        <div id=\"chat-body\" class=\"chat-body\" aria-live=\"polite\"></div>\n      </div>\n\n      <p id=\"final-line\" class=\"final-line\" aria-live=\"polite\">I'm really glad you exist.</p>\n    </section>\n  </main>\n\n  <button id=\"music-toggle\" class=\"music-toggle\" type=\"button\" aria-label=\"Toggle music\" title=\"Toggle music\">\n    <span class=\"music-toggle__icon\">🔊</span>\n  </button>\n\n  <audio id=\"bgm\" preload=\"auto\" loop=\"\">\n    <source src=\"/birthday/assets/music.mp3\" type=\"audio/mpeg\">\n    <source src=\"/birthday/assets/music.mp3\" type=\"audio/mpeg\">\n  </audio>\n\n  \n\n\n" }} suppressHydrationWarning />
    </>
  );
}
