"use client";

import Script from 'next/script';

export default function Page() {
  return (
    <>
      <Script src="/Portfolio/assets/js/main.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/mobile.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/content-loader.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/transitions.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/gestures.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/app.js" strategy="lazyOnload"  />
      <Script src="/Portfolio/assets/js/page-zoom.js" strategy="lazyOnload"  />
      <Script id="script-36-7" strategy="lazyOnload"  dangerouslySetInnerHTML={{ __html: "\n    (function() {\n\n      document.addEventListener('keydown', function(e) {\n        if (e.ctrlKey && e.shiftKey && e.key === 'P') {\n          e.preventDefault();\n          window.location.href = '/private/';\n        }\n      });\n\n      let clickCount = 0;\n      let clickTimer = null;\n      const logo = document.querySelector('.nav__logo');\n\n      if (logo) {\n        logo.addEventListener('click', function(e) {\n          clickCount++;\n\n          if (clickTimer) clearTimeout(clickTimer);\n          clickTimer = setTimeout(() => { clickCount = 0; }, 2000);\n\n          if (clickCount >= 5) {\n            e.preventDefault();\n            clickCount = 0;\n            window.location.href = '/private/';\n          }\n        });\n      }\n    })();\n  " }} />
      <head dangerouslySetInnerHTML={{ __html: "\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title>Anand Dev OS | Developer</title>\n  <meta name=\"description\" content=\"Anand Shukla - Developer building thoughtful systems. Portfolio, Lab, and Learning Log.\">\n  <meta name=\"theme-color\" content=\"#0a0a0b\">\n  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"\">\n  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap\" rel=\"stylesheet\">\n\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/variables.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/base.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/layout.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/components.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/animations.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/responsive.css\">\n  <link rel=\"stylesheet\" href=\"/Portfolio/assets/css/zoom-transitions.css\">\n" }} />
      <div dangerouslySetInnerHTML={{ __html: "\n\n  <nav class=\"nav\">\n    <div class=\"nav__inner\">\n      <a href=\"./\" class=\"nav__logo\" data-content=\"logo\"></a>\n      <button class=\"nav__toggle\" aria-label=\"Toggle menu\">\n        <span></span>\n        <span></span>\n        <span></span>\n      </button>\n      <div class=\"nav__links\" data-content=\"nav-links\">\n\n      </div>\n    </div>\n  </nav>\n\n  <section class=\"hero\">\n    <div class=\"hero__bg\">\n      <canvas id=\"particles-canvas\"></canvas>\n    </div>\n    <div class=\"container\">\n      <div class=\"hero__content\">\n        <div class=\"hero__eyebrow\" data-content=\"hero-eyebrow\"></div>\n        <h1 class=\"hero__title\">\n          <span data-content=\"hero-title\"></span>\n        </h1>\n        <p class=\"hero__subtitle\" data-content=\"hero-subtitle\"></p>\n        <p class=\"hero__philosophy\" data-content=\"hero-philosophy\"></p>\n        <div class=\"hero__cta\">\n          <a href=\"#\" class=\"btn btn--primary\" data-content=\"hero-cta-primary\"></a>\n          <a href=\"#\" class=\"btn btn--secondary\" data-content=\"hero-cta-secondary\"></a>\n        </div>\n      </div>\n    </div>\n  </section>\n\n  <section class=\"featured-projects\">\n    <div class=\"container\">\n      <div class=\"featured-projects__header reveal\">\n        <span class=\"featured-projects__eyebrow\" data-content=\"featured-eyebrow\"></span>\n        <h2 class=\"featured-projects__title\" data-content=\"featured-title\"></h2>\n      </div>\n\n      <div class=\"focus-cards-grid featured-grid\" data-content=\"featured-projects\">\n\n      </div>\n    </div>\n  </section>\n\n  <section class=\"skills-section\">\n    <div class=\"container\">\n      <div class=\"skills-grid\" data-content=\"skills-grid\">\n\n      </div>\n    </div>\n  </section>\n\n  <footer class=\"footer\">\n    <div class=\"container\">\n      <div class=\"footer__inner\">\n        <div class=\"footer__links\" data-content=\"footer-links\">\n\n        </div>\n        <p class=\"footer__copyright\" data-content=\"footer-copyright\"></p>\n      </div>\n    </div>\n  </footer>\n\n  \n  \n\n  \n\n  \n  \n  \n  \n\n  \n\n\n" }} suppressHydrationWarning />
    </>
  );
}
