/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
      "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "surface-container-lowest": "#0a0e19",
          "surface-container": "#1b1f2b",
          "primary-container": "#ff8fa3",
          "outline-variant": "#544244",
          "on-error-container": "#ffdad6",
          "primary": "#ffbac3",
          "secondary-fixed-dim": "#c9bfff",
          "primary-fixed": "#ffd9dd",
          "surface-container-low": "#171b27",
          "primary-fixed-dim": "#ffb2bd",
          "surface-container-high": "#262a36",
          "on-tertiary-fixed": "#2e014b",
          "on-primary": "#5f1127",
          "surface-bright": "#353945",
          "inverse-primary": "#9b4053",
          "outline": "#a28b8e",
          "on-secondary-container": "#b7aaff",
          "on-primary-fixed-variant": "#7d283c",
          "on-secondary-fixed": "#1a0063",
          "on-secondary-fixed-variant": "#4632a2",
          "error-container": "#93000a",
          "surface-dim": "#0f131e",
          "on-error": "#690005",
          "surface": "#0f131e",
          "surface-tint": "#ffb2bd",
          "secondary": "#c9bfff",
          "inverse-surface": "#dfe2f2",
          "on-background": "#dfe2f2",
          "on-surface": "#dfe2f2",
          "surface-variant": "#313441",
          "secondary-fixed": "#e5deff",
          "tertiary": "#e6bcff",
          "tertiary-fixed": "#f3daff",
          "secondary-container": "#4632a2",
          "inverse-on-surface": "#2c303c",
          "on-secondary": "#2f148c",
          "on-primary-container": "#782539",
          "surface-container-highest": "#313441",
          "tertiary-fixed-dim": "#e2b5ff",
          "on-surface-variant": "#dac0c3",
          "background": "#0f131e",
          "on-tertiary": "#451d61",
          "on-primary-fixed": "#400014",
          "on-tertiary-fixed-variant": "#5d357a",
          "tertiary-container": "#cd9eec",
          "on-tertiary-container": "#593176",
          "error": "#ffb4ab"
        },
        fontFamily: {
          "headline": ["Noto Serif", "serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"]
        },
        borderRadius: {
          "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"
        },
      },
    },
  };
