"use client";

import Script from 'next/script';

export default function Page() {
  return (
    <>
      <Script id="script-44-0" strategy="lazyOnload"  dangerouslySetInnerHTML={{ __html: "\n\nconst ids=[\"m1\",\"m2\",\"s1\",\"s2\",\"ms1\",\"ms2\"]\nconst els={},vals={},busy={}\n\nids.forEach(id=>{\n  const d=document.getElementById(id)\n  d.innerHTML=`\n    <div class=\"half top static\"><span>0</span></div>\n    <div class=\"half bottom static\"><span>0</span></div>`\n  els[id]={el:d,top:d.querySelector(\".top span\"),bot:d.querySelector(\".bottom span\")}\n  vals[id]=\"0\"; busy[id]=false\n})\n\nfunction flip(id,next){\n  if(busy[id]||vals[id]===next) return\n  busy[id]=true\n  const cur=vals[id],d=els[id]\n\n  d.top.textContent=next\n  d.bot.textContent=cur\n\n  const ft=document.createElement(\"div\")\n  ft.className=\"half top flip\"\n  ft.innerHTML=`<span>${cur}</span>`\n\n  const fb=document.createElement(\"div\")\n  fb.className=\"half bottom flip\"\n  fb.innerHTML=`<span>${next}</span>`\n\n  d.el.append(ft,fb)\n\n  fb.addEventListener(\"animationend\",()=>{\n    d.bot.textContent=next\n    ft.remove(); fb.remove()\n    vals[id]=next; busy[id]=false\n  },{once:true})\n}\n\nlet running=false,startTime=0,elapsed=0,raf=null\n\nfunction update(){\n  if(!running) return\n  elapsed=performance.now()-startTime\n\n  const ms=Math.floor((elapsed%1000)/10)\n  const s=Math.floor(elapsed/1000)%60\n  const m=Math.floor(elapsed/60000)\n\n  const t=\n    m.toString().padStart(2,\"0\")+\n    s.toString().padStart(2,\"0\")+\n    ms.toString().padStart(2,\"0\")\n\n  ids.forEach((id,i)=>flip(id,t[i]))\n  raf=requestAnimationFrame(update)\n}\n\nstart.onclick=()=>{\n  if(running){\n    running=false\n    start.textContent=\"Start\"\n  }else{\n    running=true\n    startTime=performance.now()-elapsed\n    start.textContent=\"Pause\"\n    update()\n  }\n}\n\nreset.onclick=()=>{\n  running=false\n  elapsed=0\n  start.textContent=\"Start\"\n  ids.forEach(id=>flip(id,\"0\"))\n}\n" }} />
      <head dangerouslySetInnerHTML={{ __html: "\n<meta charset=\"UTF-8\">\n<title>Mechanical Flip Stopwatch</title>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\n<style>\n:root{\n  --bg: radial-gradient(circle at top,#262626,#0a0a0a);\n  --card:#262626;\n  --txt:#e0e0e0;\n  --w:120px;\n  --h:170px;\n  --fs:90px;\n  --r:14px;\n  --sep:rgba(255,255,255,.5);\n  --spd:.35s;\n}\n\n*{box-sizing:border-box;margin:0;padding:0;user-select:none}\n\nbody{\n  background:var(--bg);\n  height:100vh;\n  display:flex;\n  flex-direction:column;\n  align-items:center;\n  justify-content:center;\n  font-family:system-ui,sans-serif;\n  color:var(--txt);\n}\n\n.clock{display:flex;align-items:center;gap:14px}\n.group{display:flex;gap:8px}\n.sep{font-size:60px;color:var(--sep);padding-bottom:18px}\n\n.digit{\n  width:var(--w);\n  height:var(--h);\n  position:relative;\n  perspective:1200px;\n  border-radius:var(--r);\n  box-shadow:0 10px 25px rgba(0,0,0,.5);\n}\n.half{\n  position:absolute;\n  width:100%;\n  height:50%;\n  background:var(--card);\n  overflow:hidden;\n  backface-visibility:hidden;\n  border:1px solid rgba(255,255,255,.05);\n}\n.half span{\n  position:absolute;\n  width:100%;\n  height:var(--h);\n  line-height:var(--h);\n  text-align:center;\n  font-size:var(--fs);\n  font-weight:700;\n}\n\n.top{\n  top:0;\n  border-radius:var(--r) var(--r) 0 0;\n  background:linear-gradient(to bottom,#323232,#262626);\n  transform-origin:bottom;\n}\n.top span{top:0}\n\n.bottom{\n  bottom:0;\n  border-radius:0 0 var(--r) var(--r);\n  background:linear-gradient(to bottom,#262626,#1f1f1f);\n  transform-origin:top;\n}\n.bottom span{top:-100%}\n\n.static{z-index:1}\n.flip{z-index:2}\n\n.flip.top{\n  animation:flipTop var(--spd) cubic-bezier(.4,0,.2,1) forwards;\n}\n.flip.bottom{\n  transform:rotateX(90deg);\n  animation:flipBottom var(--spd) cubic-bezier(.4,0,.2,1) forwards;\n  animation-delay:var(--spd);\n}\n\n@keyframes flipTop{to{transform:rotateX(-90deg)}}\n@keyframes flipBottom{to{transform:rotateX(0)}}\n\n.controls{margin-top:30px;display:flex;gap:20px}\nbutton{\n  background:transparent;\n  border:1px solid rgba(255,255,255,.3);\n  color:#fff;\n  padding:10px 28px;\n  border-radius:30px;\n  cursor:pointer;\n}\nbutton:hover{border-color:#fff}\n</style>\n" }} />
      <div dangerouslySetInnerHTML={{ __html: "\n\n<div class=\"clock\">\n  <div class=\"group\">\n    <div class=\"digit\" id=\"m1\"></div>\n    <div class=\"digit\" id=\"m2\"></div>\n  </div>\n  <div class=\"sep\">:</div>\n  <div class=\"group\">\n    <div class=\"digit\" id=\"s1\"></div>\n    <div class=\"digit\" id=\"s2\"></div>\n  </div>\n  <div class=\"sep\">:</div>\n  <div class=\"group\">\n    <div class=\"digit\" id=\"ms1\"></div>\n    <div class=\"digit\" id=\"ms2\"></div>\n  </div>\n</div>\n\n<div class=\"controls\">\n  <button id=\"start\">Start</button>\n  <button id=\"reset\">Reset</button>\n</div>\n\n\n\n\n\n" }} suppressHydrationWarning />
    </>
  );
}
